### ISSUE TITLE
[Security] Vulnerabilities in session id generation.

### ISSUE THREAD

**Issue by cstockton** [George3d6/Hermes#1]
Based on the writings of session ids in the [thread here](https://www.reddit.com/r/golang/comments/6jjx5i/hermes_a_self_contained_minimalist_fileserver/djf3whd/) by me. You should use AT LEAST 16 bytes of "crypto/rand" for 128 bits of entropy- exposing it through a 32 byte hex encoded string is fine, 32/256/64 would be ideal. If you need implementation help feel free to ping me. Thanks.

Edit: And it should go without saying you should fix the path traversal too :- )

-Chris

**Comment by George3d6** [comment]
I assume what you are referring to is:

`rand.New(rand.NewSource(time.Now().Unix()-time.Now().UnixNano()))`

Personally I assume this is quite secure since its generated based on quite an enormous value range, more precisely it will change 10^9 times during a minute, so a brute force attack that knows the exact minute a user logged in would still need roughly half that number of tried on average... and much more considering that the whole point of rand is to be, well, presumably... random.

I will warn you that, sadly enough, within computer science true randomness does not exist, however, if you believe that this algorithm is too weak please do suggest me a new one, what I assume is what you want is:

```
	sessionId := make([]byte, 32)
	_, err := rand.Read(sessionId)
```
... but maybe I am mistaken. Feel free to do a pull request or write the specific recommendation here.


As for the file path escaping issue, I can see people using this on servers where they don't have control over the users and users might have malicious intent, so I guess its worth fixing out of principle. I will do a "dumb" fix for that one in a second, however if you wish to recommend a better solution I am all ears.

**Comment by George3d6** [comment]
In hindsight, the discussion does bring upon me three points however:

a) Options for file to be non-delete (whereby they'd become r only for the server user) would be nice

b) Anti request-spam for those not running under nginx (Is anyone running applications exposed to the internet without something nginx-like to do the routing and the 1001 million little jobs from ssl certs to gziping and ddos protection ?)

c) It would be good to place some basic security advice in the readme (ie don't run as root, run as own user without w permission to the rest of the system...etc)

**Comment by George3d6** [comment]
Delayed a bit due to a trip, implemented as 32 bytes of "crypto/rand" send as as a 32 byte string of base 10 encoded characters. Maybe not ideal but easy to implement and with no easy to detect underlying pattern unless you assume int conversion of crypto/rand generated bytes is predictable, 32 times in a row.

**Comment by cstockton** [comment]
> unless you assume int conversion of crypto/rand generated bytes is predictable, 32 times in a row.

Nope, there is a big difference between crypto/rand and time stamps. Anyways, the session fix itself looks great, good job. I left some comments that are performance related for you inline https://github.com/George3d6/Hermes/commit/7de5bec4c887b43445278a6337ca98a1a745053c#commitcomment-22879100 (64 allocations here, probably unintentional)

The path traversal fix is not safe however
https://github.com/George3d6/Hermes/commit/2b7226ea67e6e1c0939a0741b63e17fe7fdfefb7#commitcomment-22879102 - left suggestions.
